name: motion
description: A fancy widget that applies a gyroscope or hover based motion effect to its child.
version: 1.4.2
homepage: https://cendre.me
repository: https://github.com/mrcendre/motion
issue_tracker: https://github.com/mrcendre/motion/issues?q=is%3Aissue+is%3Aopen

flutter:
  plugin:
    platforms:
      android:
        package: me.cendre.motion.plugin
        pluginClass: MotionPlugin
      ios:
        pluginClass: MTMotionPlugin
      web:
        default_package: motion_web

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  motion_web: ^1.4.0
  motion_platform_interface: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
